
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

<table bgcolor="gray" width="100%">
<tr>
<td>
<h2 align="center"><font color="#ffffff" ><b>YALAVARTHI</b></font></h2>
</td>
</tr>
</table>
<br>
Greeting from YALAVARTHI PASSWORD MANAGEMENT
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Hi welcome to <b>yalavarthi constructions pvt ltd</b> thanks for choosing change password request
.your OTP IS<b style="color:red"> OTP IS:12345 </b>. this otp is valid till only 5 minutes.

Malware sent via email messages can be quite destructive.
Phishing emails sent to employees often contain malware in attachments 
designed to look like legitimate documents or include hyperlinks that lead 
to websites that serve malware. Opening an email attachment or clicking on a
link in an email
 can be all that it takes for accounts or devices to become compromised.
 <br><br><br>
 Thanks & Regards<br>
 SravanKumar<br>
 9032181261
 <br><br><br>
<table bgcolor="#d4d4d4" width="100%">
<tr>
<td>
<font color="#ff6600"><b>This mail is AutoGenerated Please do not reply" 
</font>
<font color="#800080">YALAVARTHI PVT LTD.</font> .</b> 
</td>
</tr>
</table>
</body>
</html>